### ISSUE TITLE
Perfect Support RecyclerView

### ISSUE THREAD

**Issue by IamKing** [woxingxiao/BubbleSeekBar#101]
我很好奇你这个优秀的一个SeekBar为啥不能支持RecyclerView。你的组件已经用在我的APP上，为了解决这个问题，特意瞟了一眼源码。既然是用WindowManager来显示BubbleView, 那么我推测就是WindowManager.LayoutParams的y值设置的不对，不能根据是在屏幕中点击位置来确定，所以改写了下面showBubble()方法。重载了这个方法如下：

    `private void showBubble(int rawY, int y) {
        if (mBubbleView == null || mBubbleView.getParent() != null) {
            return;
        }

        mBubbleCenterRawSolidY = rawY - y - mBubbleView.getMeasuredHeight() - getMeasuredHeight();
        mBubbleCenterRawSolidY += dp2px(4);
        if (BubbleUtils.isMIUI()) {
            mBubbleCenterRawSolidY += dp2px(4);
        }

        Context context = getContext();
        if (context instanceof Activity) {
            Window window = ((Activity) context).getWindow();
            if (window != null) {
                int flags = window.getAttributes().flags;
                if ((flags & WindowManager.LayoutParams.FLAG_FULLSCREEN) != 0) {
                    Resources res = Resources.getSystem();
                    int id = res.getIdentifier("status_bar_height", "dimen", "android");
                    mBubbleCenterRawSolidY += res.getDimensionPixelSize(id);
                }
            }
        }

        mLayoutParams.x = (int) (mBubbleCenterRawX + 0.5f);
        mLayoutParams.y = (int) (mBubbleCenterRawSolidY + 0.5f);

        System.out.println("33====" + mLayoutParams.y);

        mBubbleView.setAlpha(0);
        mBubbleView.setVisibility(VISIBLE);
        mBubbleView.animate().alpha(1f).setDuration(isTouchToSeek ? 0 : mAnimDuration)
                .setListener(new AnimatorListenerAdapter() {
                    @Override
                    public void onAnimationStart(Animator animation) {
                        mWindowManager.addView(mBubbleView, mLayoutParams);
                    }
                }).start();
        mBubbleView.setProgressText(isShowProgressInFloat ?
                String.valueOf(getProgressFloat()) : String.valueOf(getProgress()));
    }`
然后用这个方法替换onTouchEvent中的MotionEvent.ACTION_DOWN分支中的showBubble方法，完美解决在RecyclerView中使用的问题：
  
        `@Override
       public boolean onTouchEvent(MotionEvent event) {
        switch (event.getActionMasked()) {
            case MotionEvent.ACTION_DOWN:
                performClick();
                getParent().requestDisallowInterceptTouchEvent(true);

                isThumbOnDragging = isThumbTouched(event);
                if (isThumbOnDragging) {
                    if (isSeekBySection && !triggerSeekBySection) {
                        triggerSeekBySection = true;
                    }
                    if (isAlwaysShowBubble && !triggerBubbleShowing) {
                        triggerBubbleShowing = true;
                    }
                    if (!isHideBubble) {
                          @@showBubble((int) event.getRawY(), (int) event.getY());
                    }

                    invalidate();
                } else if (isTouchToSeek && isTrackTouched(event)) {
                    isThumbOnDragging = true;
                    if (isSeekBySection && !triggerSeekBySection) {
                        triggerSeekBySection = true;
                    }
                    if (isAlwaysShowBubble) {
                        hideBubble();
                        triggerBubbleShowing = true;
                    }

                    if (isSeekStepSection) {
                        mThumbCenterX = mPreThumbCenterX = calThumbCxWhenSeekStepSection(event.getX());
                    } else {
                        mThumbCenterX = event.getX();
                        if (mThumbCenterX < mLeft) {
                            mThumbCenterX = mLeft;
                        }
                        if (mThumbCenterX > mRight) {
                            mThumbCenterX = mRight;
                        }
                    }

                    mProgress = calculateProgress();

                    if (!isHideBubble) {
                        mBubbleCenterRawX = calculateCenterRawXofBubbleView();
                         showBubble((int) event.getRawY(), (int) event.getY());
                    }
                    invalidate();
                }
                dx = mThumbCenterX - event.getX();
                break;`

**Comment by woxingxiao** [comment]
我使用WindowManager动态添加气泡和更新气泡位置，列表View的话稍微变动，item便需要去获取自己的实时屏幕坐标以便更新位置，这对性能的开销是巨大的，得不偿失。本库的初衷就是少量（小于3个）使用的场景。
“特意瞟了一眼源码”，做好饭没有喂到您嘴里，招呼不周，您受累了~

**Comment by IamKing** [comment]
“我使用WindowManager动态添加气泡和更新气泡位置”
如果不是所有的BubbleView always show，用WindowManager每次只控制一个View的显示和隐藏，而BubbleView的位置只有在Action_down的时候才会去获取，跟获取X和Y的值是一样的，完全不用考虑性能问题。
“本库的初衷就是少量（小于3个）使用的场景。”  ->....
.
