### ISSUE TITLE
View is not aligned

### ISSUE THREAD

**Issue by bernaferrari** [woxingxiao/BubbleSeekBar#102]
I am having a lot of problems because the BubbleSeekBar isn't vertical aligned with other views, when using ConstraintLayout and LinearLayout (so, this might be valid for all).

Is this by design, or is there a way to fix? I would love to have the bar aligned in the center.

<img width="810" alt="screen shot 2018-01-15 at 16 48 23" src="https://user-images.githubusercontent.com/351125/34957300-28bd683c-fa14-11e7-9516-7a448770b2ab.png">

**Comment by woxingxiao** [comment]
I will fix it in next version. 
Besides, if you are eager to fix it, here is the way: find the method `onMeasure()`, then delete the line `height += mTextSpace * 2;`.

**Comment by bernaferrari** [comment]
Thanks!
