### ISSUE TITLE
Please Use Tag Release

### ISSUE THREAD

**Issue by DanieleBelfiore** [woxingxiao/BubbleSeekBar#106]
Hello,
thanks for your developments.

Only one thing I would suggest to you: you could use tag release for every new release commited.

Last release tag is the 2.1 version but your actual release version is 3.14.

This behaviour permit to us to find more quickly the new releases and even your GitHub page is more standard for GitHub specifications.

Really appreciate that.

Thanks in advance.

**Comment by woxingxiao** [comment]
Noted and thx.
