### ISSUE TITLE
Issue if view moved to next screen

### ISSUE THREAD

**Issue by Dcodechef** [woxingxiao/BubbleSeekBar#11]
Thank you for providing the library.

There is crash if we left pointer in between and move to next screen.

Is there any chance to make seek bar animation fast, if it's left in between ?

JNI DETECTED ERROR IN APPLICATION: can't call void android.view.View.setTranslationZ(float) on null object

**Comment by woxingxiao** [comment]
The least version has been released, which was added a new  `anim_duration` attribute you can customize duration of animation.
