### ISSUE TITLE
Bubble Tracks Switched

### ISSUE THREAD

**Issue by searchy2** [woxingxiao/BubbleSeekBar#110]
![maxthonsnap20180205214125](https://user-images.githubusercontent.com/19896174/35840685-69163a9e-0abd-11e8-865b-7ea995045093.png)
I am using this beautiful library as a progress bar. Unfortunately, the tracks are switched! Track 1 is the foreground track but looks like the background track. Track 2 looks like the foreground track but is actually the background track. This becomes apparent when the button's radius is set to 0. If only the two were reversed, it would work as a progress bar too! 

Is there anything I can do?

**Comment by woxingxiao** [comment]
Make sure the color of the thumb as the same as the second track's color.

**Comment by searchy2** [comment]
I can set RTL true but that's no solution. What I ended up going with is setting the thumb the same color as the second track. Unfortunately, the thumb's radius cannot be decreased below a certain point.

**Comment by searchy2** [comment]
Haha, you replied just as I was typing my reply. There's another more pressing issue that I hope you can answer. Is there a way to remove the decimal from the Bubble popup? I have no need of the decimal but there's no apparent way to remove it.

**Comment by woxingxiao** [comment]
You mean to hide the bubble?

**Comment by searchy2** [comment]
No, the bubble's number has a decimal like "47.0". Can I have it just display "47"?

**Comment by searchy2** [comment]
Ok, that last question I managed to answer. It seems when you set the progress by configuring, it displays the text without the trailing decimal. However, when set from XML or via .setProgress, the number has a trailing decimal. Weird! 

Thanks for the great library!
