### ISSUE TITLE
BubbleSeekBar应用在RecyclerView中的问题

### ISSUE THREAD

**Issue by FunnyLee** [woxingxiao/BubbleSeekBar#111]
当我在RecyclerView中使用BubbleSeekBar，我设置了app:bsb_touch_to_seek="false"属性。但是如果上下滑动RecyclerView的条目，手机放在进度条位置开始滑动条目，结果没法滑动RecyclerView。只要当手指放在进度以外的位置，才能顺利滑动RecyclerView条目
这是什么原因了？谢谢

**Comment by woxingxiao** [comment]
因为拦截了事件呗。后续可以优化下对竖直方向的判断

**Comment by FunnyLee** [comment]
如何判断竖直方向的滑动啊？
