### ISSUE TITLE
Pointer problem in viewpager

### ISSUE THREAD

**Issue by SalaSuresh** [woxingxiao/BubbleSeekBar#113]
Multiple pointers are creating in viewpager while sliding layouts.
Please let me know how to overcome this
![device-2018-02-28-194820](https://user-images.githubusercontent.com/10635332/36792347-5ff570f0-1cc0-11e8-8ea4-cb3dca347cc6.png)

**Comment by woxingxiao** [comment]
Is every page containing a `BubbleSeekBar`, and have you set `bsb_always_show_bubble = true`?

**Comment by SalaSuresh** [comment]
Hi.. yes.. In my case I need to show bubble always. Because of that I
added bsb_always_show_bubble
= true? In all pages. And also it's causing animation jerk during scrolling
pages..

Thank you

Regards
Suresh.

On 03-Mar-2018 1:42 PM, "Xiao" <notifications@github.com> wrote:

Is every page containing a BubbleSeekBar, and have you set
bsb_always_show_bubble
= true?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/woxingxiao/BubbleSeekBar/issues/113#issuecomment-370129005>,
or mute the thread

**Comment by woxingxiao** [comment]
Oh, I see. The multiple bubbles are all showing on the screen because they have been added to `Window` by the `WindowManager`.  So the only solution is setting `bsb_always_show_bubble = false`.

**Comment by SalaSuresh** [comment]
Thanks for the replay.. I tried in that way also in that case the pointer
is not moving to user selected position. It is always sticking with either
start point or end point..

Please let me know once issue is fixed..

Thanks..

Regards,
Suresh.

**Comment by woxingxiao** [comment]
Have you try to listen to the `ViewPager`'s page-change-event and do this:
```java
@Override
 public void onPageSelected() { 
      mBubbleSeekBar.correctOffsetWhenContainerOnScrolling();
  }
```
?

**Comment by SalaSuresh** [comment]
Hi.. I used above code, but still I'm facing same animation jerk problem (To overcome this problem I did temporary fix.. )

@Override
            public void onPageScrollStateChanged(int state) {
                if (ViewPager.SCROLL_STATE_IDLE == state) {
                    updateSeekBar();
                }
            }

 private void updateSeekBar() {
        mSeekStatus.setProgress(array of progress);
}

**Comment by woxingxiao** [comment]
I reproduced the problem. I'll investigate it.

**Comment by SalaSuresh** [comment]
Thanks for the replay.. please let me know once issue is fixed..

Regards,
Suresh

**Comment by woxingxiao** [comment]
@SalaSuresh 
Hi, this bug has been fixed. Please check the latest version out. 
Btw, there is no need to listen to the page-change-event or correct the offset anymore in `ViewPager`.

**Comment by SalaSuresh** [comment]
Sure.. I'll check and I'll update you as soon as possible.

**Comment by SalaSuresh** [comment]
Hi.. I checked with latest version 3.16, but still I'm facing same problem. I'm providing my demo project gist and along with video also. Please find root cause and fix it as soon as possible.

Gist:
https://gist.github.com/SalaSuresh/1e597050e1bfbb356adc5ba83324fc3a

Video:
https://drive.google.com/file/d/1nLzZ4ePOHEqiv8i2yqb61wSUdVO2PG8b/view?usp=sharing

Regards,
Suresh.

**Comment by woxingxiao** [comment]
bsb_always_show_bubble = false

**Comment by SalaSuresh** [comment]
Hi.. But in my case I have to show bubble always in all slides

Regards,
Suresh.

**Comment by woxingxiao** [comment]
Sorry, I'm afraid I can't help you at the moment.
