### ISSUE TITLE
Is there any way to update max/min values programatically?

### ISSUE THREAD

**Issue by ardevd** [woxingxiao/BubbleSeekBar#118]
Currently, it doesnt seem to be a way to update the seekbar max/min values if defined in XML. Am I missing something? Would be very useful to be able to dynamically alter this at runtime.

**Comment by woxingxiao** [comment]
You missed the comprehensive README.

**Comment by ardevd** [comment]
Ive read through the README but haven't been able to find any answers. Could you point me in the right direction please?

**Comment by EvaZhang321** [comment]
only enhances version can dynamecally alter max/min values
