### ISSUE TITLE
Selected Progress text is not changing color for custom text.

### ISSUE THREAD

**Issue by poojakaluskar** [woxingxiao/BubbleSeekBar#123]
First of all, great library. Loved it. 

Now, I want seek bar with custom text below Seekbar.
Using the sample code
`seekBar.setCustomSectionTextArray(new BubbleSeekBar.CustomSectionTextArray() {
            @NonNull
            @Override
            public SparseArray<String> onCustomize(int sectionCount, @NonNull SparseArray<String> array) {
                array.clear();
                array.put(0,"NA");
                array.put(1, "BEG");
                array.put(2, "EXP");
                array.put(3, "ADV");
                return array;
            }`

Now if I use this code then selected progress text does not change color. It using the default color.
<img width="336" alt="screen shot 2018-03-28 at 11 17 00 am" src="https://user-images.githubusercontent.com/12078962/38042374-d8a1a806-3279-11e8-885d-65d715f476b7.png">

If I remove my custom text and use the number then it is changing the color.
<img width="331" alt="screen shot 2018-03-28 at 11 16 48 am" src="https://user-images.githubusercontent.com/12078962/38042384-dda2045e-3279-11e8-9e41-2fb64a00b238.png">

Let me know if I should submit more code. Thank you.

**Comment by woxingxiao** [comment]
Designed so.

**Comment by Asykur** [comment]
Any solution for this case?
