### ISSUE TITLE
rtl option irreversible

### ISSUE THREAD

**Issue by hgourvest** [woxingxiao/BubbleSeekBar#125]
using BubbleConfigBuilder you can change to RTL but you can't revert this setting to LTR.
I would suggest this:

    public BubbleConfigBuilder rtl(boolean value) {
        this.rtl = value;
        return this;
    }

**Comment by woxingxiao** [comment]
The default is from left to right. Why bother?

**Comment by hgourvest** [comment]
I need to let the user change the reading direction when he want, it is for a comic book reader.

**Comment by woxingxiao** [comment]
Suggestion accepted!

**Comment by hgourvest** [comment]
thanks!
