### ISSUE TITLE
滑动问题

### ISSUE THREAD

**Issue by fearlesstrek** [woxingxiao/BubbleSeekBar#126]
使用BubbleSeekbar的时候，设置0-20的范围。但是滑动的时候0-3之间的1和2一直没办法滑动出来
也就是从0滑到1 2的时候直接跳到3
 <com.xw.repo.BubbleSeekBar
            android:id="@+id/mediaSeekBar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="20dp"
            android:layout_marginRight="20dp"
            app:bsb_auto_adjust_section_mark="true"
            app:bsb_hide_bubble="true"
            app:bsb_max="20"
            app:bsb_min="0"
            app:bsb_second_track_color="@color/seekbar_second_color"
            app:bsb_section_count="20"
            app:bsb_section_text_color="@color/seekbar_second_color"
            app:bsb_section_text_position="bottom_sides"
            app:bsb_section_text_size="22dp"
            app:bsb_seek_step_section="true"
            app:bsb_show_section_text="true"
            app:bsb_show_thumb_text="true"
            app:bsb_thumb_color="@color/ts_white"
            app:bsb_thumb_text_color="@color/seekbar_second_color"
            app:bsb_thumb_text_size="22dp"
            app:bsb_touch_to_seek="true"
            app:bsb_track_color="@color/seekbar_color"
            app:bsb_track_size="6px"/>

**Comment by woxingxiao** [comment]
我还原了你的布局发现没有任何问题。你再仔细确认下，如果仍有问题麻烦录个屏。

**Comment by fearlesstrek** [comment]
屏幕问题
