### ISSUE TITLE
Databinding issues

### ISSUE THREAD

**Issue by Gonzom** [woxingxiao/BubbleSeekBar#127]
I was converting my code to use databinding and I was having some trouble because of the ConfigBuilder.

Databinding uses the property you gave and searches the java code for the setter.
First problem is when the setter and xml property aren't the same name.

This I was able to fix with:
```
@BindingMethods({
        @BindingMethod(type = com.xw.repo.BubbleSeekBar.class,
                attribute = "app:bsb_progress",
                method = "setProgress"),
```

But when I wanted to do the same for app:bsb_section_count, I couldn't because that is under `getConfigBuilder()` (unless I missed another method).

If you could add a setter for these xml properties this view would work with databinding

**Comment by eth5** [comment]
I confirm DataBinging does not work in some methods :(
`android: onProgressChanged = "@ {(seekBar, i, f) -> ...)}"`

**Comment by atasoglou** [comment]
same here, `android:enabled`, `android:progress`, `android:onProgressChanged`, etc all not supported

**Comment by atasoglou** [comment]
OK with the hint of @Gonzom, I implemented also my own stuff to at least have two way data-binding for the progress and one way data biding for the View.Enable. Anyone interested, [here is a gist](https://gist.github.com/atasoglou/40924f2e5716dac0cfd20eae620ce30f).

**Comment by woxingxiao** [comment]
Hey guys, fully `DataBinding` support will be added in next big version.

**Comment by sinansonmez** [comment]
I am still having the same problem. How is it solved?
