### ISSUE TITLE
SeekBar with 2 thumbs (range)

### ISSUE THREAD

**Issue by ntarocco** [woxingxiao/BubbleSeekBar#129]
I am using your SeekBar, very nice, good job!
I was wondering if it would possible/easy to add an option to have 2 thumbs, to define a range, similar to this one: https://stackoverflow.com/questions/5795773/android-seekbar-with-two-thumbs

Any plan to add this? If you think that it is easy to do, I can create a PR.

**Comment by woxingxiao** [comment]
Thanks for your great idea. But I don't think a repo should have too many features, I prefer it's pure. Maybe I'll start a new RankBubbleSeekBar open project in the future, or you can do it.
