### ISSUE TITLE
bug for min attribute 

### ISSUE THREAD

**Issue by lzq1126** [woxingxiao/BubbleSeekBar#13]
When min is set to 500, and max is set to 1000, display error.

**Comment by woxingxiao** [comment]
你在java代码中设置的吧，我试了确实有这个问题，感谢反馈。xml中设置是正常的。下个版本修复。

**Comment by woxingxiao** [comment]
The version v1.9 has fixed this bug.

**Comment by lxfwelldone** [comment]
还是有这个bug，我设置min =25 max=55 初始显示是正确的，滚动就绘制出错了

**Comment by lxfwelldone** [comment]
我是在 getProgressOnActionUp 方法中 判断 值 是否小于35, 如果小于 就 设置为25，然后就绘制出错了
