### ISSUE TITLE
Add missing enabled attribute to the xml

### ISSUE THREAD

**Issue by Gonzom** [woxingxiao/BubbleSeekBar#130]
There is an open [bug report](https://issuetracker.google.com/issues/38305745) regarding the issue of View not having an xml option to set its enabled status.

What this means is that BubbleSeekBar cannot set its enabled status via xml as it extends View.

A fix that should work is adding
1. `<attr name="android:enabled" />` to the attr.xml
2. `setEnabled(typedArray.getBoolean(R.styleable.BubbleSeekBar_android_enabled, isEnabled()));` to BubbleSeekBar.java

```
   public BubbleSeekBar(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);

        TypedArray a = context.obtainStyledAttributes(attrs, R.styleable.BubbleSeekBar, defStyleAttr, 0);
        setEnabled(a.getBoolean(R.styleable.BubbleSeekBar_android_enabled, isEnabled()));
}
```

**Comment by woxingxiao** [comment]
Noted. Thx.
