### ISSUE TITLE
BottomSheetFragment problems

### ISSUE THREAD

**Issue by Angels-group** [woxingxiao/BubbleSeekBar#135]
![image](https://user-images.githubusercontent.com/1552042/39996972-ec44e6a4-5789-11e8-9ed7-dd784e0024ec.png)

**Comment by woxingxiao** [comment]
Sorry, it's been busy recently.
I had tried to put a `BubbleSeekBar` in a `BottomSheetDialogFragment`, but it didn't reappear the problem you reported. I can't diagnose it unless you offer me more information.

**Comment by mmswide** [comment]
BubbleSeekBar in a BottomSheetDialogFragment is not working on my side, too.
Can you provide some example code for me?
Thanks.
