### ISSUE TITLE
Unable to add values for seekbar section text

### ISSUE THREAD

**Issue by Gowthamsubramaniam94** [woxingxiao/BubbleSeekBar#139]
@woxingxiao How can i get Custom section text array? If i added a custom text in seekbar, i can't able to get custom section text progress from "setOnProgressChangedListener". 

For Eg: If i added [0,15,20,25] as custom section text with section count as 3. I can't getting the selected position's custom text. I'm getting only 8 as the progress in "setOnProgressChangedListener". Because 25/3 = 8.333, so progress selected in the first position is 8. 

Here, I need solution to get the custom section text as selected progress value.

**Comment by woxingxiao** [comment]
For now, this is not a bug, because the progress is linear. Perhaps it will be a new feature in the future.
