### ISSUE TITLE
Seek onClick

### ISSUE THREAD

**Issue by amorenew** [woxingxiao/BubbleSeekBar#14]
I tried to click any place on the track but it doesn't seek to the clicked position
i think it would be nice if you added seek on touching any position

**Comment by woxingxiao** [comment]
Good suggestion, I'll add it in next version.

**Comment by amorenew** [comment]
Thanks good work

**Comment by woxingxiao** [comment]
Hey man, the new version just released has added this feature.

**Comment by amorenew** [comment]
I tested the new feature but it need a minor enhancement
      ```
  <item name="bsb_auto_adjust_section_mark">true</item>
        <item name="bsb_show_section_mark">true</item>
        <item name="bsb_section_count">16</item>
        <item name="bsb_max">17</item>
        <item name="bsb_min">1</item>
        <item name="bsb_touch_to_seek">true</item>
```
![device-2017-02-22-125602](https://cloud.githubusercontent.com/assets/2842459/23206506/ec1ab34c-f8fe-11e6-8c61-69b0f967942d.png)
![device-2017-02-22-125852](https://cloud.githubusercontent.com/assets/2842459/23206505/ec18e40e-f8fe-11e6-9366-de59ed1f1dac.png)

**Comment by amorenew** [comment]
if i remove    
`     <item name="bsb_show_section_mark">true</item>
`the auto adjust doesn't work  well
`        <item name="bsb_auto_adjust_section_mark">true</item>
`

**Comment by woxingxiao** [comment]
I designed to like this way. If you don't show the section mark, someone seeks the bar sometimes auto-scrolling to a position not he wanted, which is kind of odd.
Actually, you don't need adjust to some section mark, people rather care about value of progress than some position on the bar.
