### ISSUE TITLE
设置两个属性 app:bsb_seek_by_section="true" app:bsb_show_thumb_text="true"后，thumb下部的文本显示错误，原因找到

### ISSUE THREAD

**Issue by shengMR** [woxingxiao/BubbleSeekBar#141]
![mu 5 1 ux 7jk 0ta5](https://user-images.githubusercontent.com/23476485/41955834-49f07352-7a14-11e8-9d8f-4084b4c898eb.png)

原因是在processProgress方法内对返回数值做了操作，现在不是很理解这个操作的意义，请教下博主
这个`  if (progress >= mPreSecValue) { // increasing
                if (progress >= mPreSecValue + half) {
                    mPreSecValue += mSectionValue;
                    return mPreSecValue;
                } else {
                    return mPreSecValue;
                }
            } else { // reducing
                if (progress >= mPreSecValue - half) {
                    return mPreSecValue;
                } else {
                    mPreSecValue -= mSectionValue;
                    return mPreSecValue;
                }
            }`

**Comment by woxingxiao** [comment]
你使用的是最新版吗，我试了没有问题啊。。

**Comment by shengMR** [comment]
嗯啊，最新的，直接在xml设置这样

`<com.xw.repo.BubbleSeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="50dp"
        app:bsb_hide_bubble="true"
        app:bsb_seek_by_section="true"
        app:bsb_show_section_mark="true"
        app:bsb_show_thumb_text="true"/>`

然后直接从0滑到100，就会出现文本不一致了，不要设置监听，设置监听就正常了

**Comment by woxingxiao** [comment]
@shengMR 
找到原因了，在`bsb_hide_bubble="true"`前提下，seeking时未调用`getProgress()`（最终是`processProgress()`）方法更新上一次滑到的位置，所以造成了数值不对应。3.18已经修复，感谢issue.

**Comment by woxingxiao** [comment]
不是吧老铁，我测了n遍。更新最新没有，不行清哈缓存。。

**Comment by shengMR** [comment]
哈哈哈，我卸载重装，然后设置了 implementation 'com.xw.repo:bubbleseekbar:3.18-lite'
还是会啊，滑动快就一下子出现了

**Comment by shengMR** [comment]
` if (progress >= mPreSecValue) { // increasing
                if (progress >= mPreSecValue + half) {
                    mPreSecValue += mSectionValue;
                    return mPreSecValue;
                } else {
                    return mPreSecValue;
                }
            } else { // reducing
                if (progress >= mPreSecValue - half) {
                    return mPreSecValue;
                } else {
                    mPreSecValue -= mSectionValue;
                    return mPreSecValue;
                }
            }`
这部分代码搞的鬼，不过现在不知道这段代码的意义耶，只能知道这是增加减少一段数据

**Comment by woxingxiao** [comment]
SeekBySection，也就是需要显示出来的progress是跳跃的效果（如0，10，20，...），这段代码用于判断progress是否越过两个section间的一半，比如0到10，如果越过5就显示10，否则显示0。这个库的属性组合太多了，完全没有测试过飞快手乱滑。
暂时解决方案就是设置一个监听，`processProgress()`会反复调用3次基本可以确保数值对应。待我有时间再寻求终极方案。
