### ISSUE TITLE
Set maximum value dynamically

### ISSUE THREAD

**Issue by arifNislam** [woxingxiao/BubbleSeekBar#143]
Though it is said in document that lite version has min, max getter/setter but I did not find any method for set maximum value programmatically . I'm using version 3.16-lite

**Comment by woxingxiao** [comment]
Then enhanced version is better for you.

**Comment by arifNislam** [comment]
I don't have any problem to use enhanced version. But it'll be great if lite version have getter / setter for min, max and progress.
