### ISSUE TITLE
气泡位置

### ISSUE THREAD

**Issue by liuwenzhi1** [woxingxiao/BubbleSeekBar#144]
您好 请问气泡的位置显示的不正确，刻度条把气泡分成上下两部分了

**Comment by woxingxiao** [comment]
哪个版本？怎么用的代码贴下撒

**Comment by liuwenzhi1** [comment]
@woxingxiao   版本号 3.18 <com.xw.repo.BubbleSeekBar
        android:id="@+id/hint_seek_bar"
        android:layout_width="1384px"
        android:layout_height="wrap_content"
        android:layout_below="@id/hint_volume"
        android:layout_marginLeft="268px"
        android:layout_marginTop="64px"
        app:bsb_bubble_color="@color/colorText"
        app:bsb_hide_bubble="true"
        app:bsb_second_track_color="@color/colorText"
        app:bsb_thumb_color="@color/colorText"
        app:bsb_track_color="#707070" />  下载过来的代码没有问题 但是把代码copy到我的项目中 气泡位置就不对了

**Comment by liuwenzhi1** [comment]
@woxingxiao  请问能够动态设置 max吗？

**Comment by woxingxiao** [comment]
什么叫“下载过来的代码”？
什么叫“copy来的代码”？
设置了app:bsb_hide_bubble="true"怎么会出现气泡？
为什么你要用px做单位？
为什么你不认真阅读我的文档，里面有详细说明，包括max？

**Comment by liuwenzhi1** [comment]
@woxingxiao 1：就是你上传的项目  2：从你项目中 copy布局到我的项目中，3：因为气泡位置不对我才隐藏的，4：px是因为 我用了autolyout 然后设计给的也是px ，5是我的失误我后面看到了

**Comment by woxingxiao** [comment]
依赖没问题就行
