### ISSUE TITLE
SectionTextPosition 能否设置在刻度轴的上方？

### ISSUE THREAD

**Issue by gdhucoder** [woxingxiao/BubbleSeekBar#145]
您好，想把TextPosition设置在刻度轴上方，请问如何实现？ 

可供选择的有以下三种，但没有例如TOP_SECTION_MARK
TextPosition.SIDES;
TextPosition.BOTTOM_SIDES;
TextPosition.BELOW_SECTION_MARK;

**Comment by woxingxiao** [comment]
刻度会被气泡挡住，所以没设计这种。

**Comment by gdhucoder** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
您好！谢谢您的回复！如果我不显示气泡的话，不就挡不住了么？请问有没有什么变通的方法实现我想要的效果呢？ 样子见附件图片。


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    
祝好！胡国栋18948345257

                


    在2018年7月15日 10:44，Xiao<notifications@github.com> 写道： 


刻度会被气泡挡住，所以没设计这种。

**Comment by woxingxiao** [comment]
抱歉，暂不支持。

**Comment by gdhucoder** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
好的，明白，谢谢！ 感谢您做出这么好用的工具。


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    
    
        font{
            line-height: 1.6;
        }
    
祝好！胡国栋18948345257

                


    在2018年7月15日 10:58，Xiao<notifications@github.com> 写道： 


抱歉，暂不支持。
