### ISSUE TITLE
Can i change seekbar color in 5 different color according to section like you have given text value array

### ISSUE THREAD

**Issue by jishantmed** [woxingxiao/BubbleSeekBar#147]

**Comment by woxingxiao** [comment]
Demo4 is not understandable to you?

**Comment by jishantmed** [comment]
in demo4 color is getting cahnged o progress bar change. I want all different color for all section in static state too.
![screenshot_20180720-101454](https://user-images.githubusercontent.com/41432242/42983809-619997be-8c06-11e8-98d4-2a5dbeb30f4a.png)

Please check this image for reference @woxingxiao

**Comment by woxingxiao** [comment]
Not supported.
