### ISSUE TITLE
这个算bug么

### ISSUE THREAD

**Issue by fcscr126608** [woxingxiao/BubbleSeekBar#148]
![image](https://user-images.githubusercontent.com/35981460/43031389-4e1c9a38-8cd3-11e8-817c-d74db9088def.png)
MIUI 9.6  Android 8.0

**Comment by woxingxiao** [comment]
你什么机型，我也9.6，8.0完全正常啊

**Comment by woxingxiao** [comment]
解决了，感谢反馈。
