### ISSUE TITLE
[Enhancement] Magnetic seek and Pop-Up

### ISSUE THREAD

**Issue by ixig** [woxingxiao/BubbleSeekBar#15]
This is really nice ... but I would like to suggests two enhancements:

1. Oftentimes we want to use a seek bar which has only a discrete number of steps (e.g. 0,1, ...,10). Provide support for this via an attribute (e.g. number_steps). Of course, if set, the seek button should behave magnetically as well, i.e. it should not slide smoothly but snap to the nearest step position.

2. It would be very nice for compact UIs if you can have an option whereby you show the value of the seekbar as text on the seek button itself (which can be configured to be either a circle or rounded rectangle). Then, when the user drags the button, you can pop up your bubble view to indicate the seek value _temporarily_ (because the finger will be blocking the button)

**Comment by woxingxiao** [comment]
Thanks for your wonderful suggestions, which would be carefully considered.
