### ISSUE TITLE
android.view.WindowManager$BadTokenException  Unable to add window android.view.ViewRootImpl$W@f6e6e8b -- permission denied for this window type

### ISSUE THREAD

**Issue by fcscr126608** [woxingxiao/BubbleSeekBar#157]
你好，请问这个是权限问题吗?
![image](https://user-images.githubusercontent.com/35981460/46239706-cc1e0980-c3ce-11e8-8491-9507142d2f43.png)

**Comment by woxingxiao** [comment]
看你这个马赛克包名的意思，是拿去改造了。拉取最新的替换就对了。

**Comment by fcscr126608** [comment]
@woxingxiao 是的，以前直接下载复制到view包下了。那我拉取最新的替换一下。试试看！谢谢！

**Comment by woxingxiao** [comment]
所以正常了吗沃日

**Comment by fcscr126608** [comment]
不行啊大哥

**Comment by woxingxiao** [comment]
我就是MIUI，不会报错，你可以试试我的sample.apk，如果没问题你就自己找找原因。另外，麻烦你把话说明白，半句话没有重点真的神烦（一般这种都懒得回）。
