### ISSUE TITLE
可否增加自定义首尾文字

### ISSUE THREAD

**Issue by MAIMIHO** [woxingxiao/BubbleSeekBar#17]
多谢贡献优雅易用的控件, 如果能提供自定义首尾文字就更好了.

**Comment by woxingxiao** [comment]
两端的文字？完全可以用两个TextView啊，岂不是更灵活方便？

**Comment by MAIMIHO** [comment]
不好意思, 我的描述不准确. 有一个需求是这样的. 用TextView不同屏幕上不容易对齐. 
![image](https://cloud.githubusercontent.com/assets/18633356/23821799/6c6fd7d0-0678-11e7-88b5-a828fcabec20.png)

**Comment by woxingxiao** [comment]
ok，下个版本加

**Comment by woxingxiao** [comment]
新版已发布，可满足该需求 : )

**Comment by MAIMIHO** [comment]
厉害了!
![image](https://cloud.githubusercontent.com/assets/18633356/23832002/8564706c-0767-11e7-8662-4c69ca336a26.png)
![image](https://cloud.githubusercontent.com/assets/18633356/23832003/86698a4c-0767-11e7-85a9-7b562db8e95f.png)
![image](https://cloud.githubusercontent.com/assets/18633356/23832004/87df556e-0767-11e7-897e-a2d44e865804.png)
