### ISSUE TITLE
你好,请问setProgressRange()方法min和max能否设置float类型

### ISSUE THREAD

**Issue by LaLaTiao** [woxingxiao/BubbleSeekBar#18]
因业务需要,设置seekBar,min为0,max为小数...
但是该方法只能设置int数据类型
在源码669行有对3参数传入的progress和转换成float的max进行比较
请问能否干脆添加一个可以设置float类型参数的方法
谢谢!

**Comment by woxingxiao** [comment]
新版已完全支持float，即将发布，敬请期待哦 ；)
