### ISSUE TITLE
Right to Left!

### ISSUE THREAD

**Issue by khaledkhj** [woxingxiao/BubbleSeekBar#2]
Thank you for this great library.
Is it possible to reverse direction of this bar, meaning that to start from right and end it on the left side?

**Comment by woxingxiao** [comment]
I tried to add a new attribute, but it turned out making codes more complex to read and maintain. My suggestion is that you can solve it out by changing my codes, if you really need this attribute.

**Comment by khaledkhj** [comment]
ok cool .. I will give it a try.
Thank you.

**Comment by woxingxiao** [comment]
If you need any help, please e-mail me : )
