### ISSUE TITLE
显示不对。

### ISSUE THREAD

**Issue by cuiyue1988** [woxingxiao/BubbleSeekBar#20]
你好， 我现在有个需求是要某个位置强制停留。 比如100元~30000元。 用户必须以100为单位递增。
但是我配置了。发现进度条有问题。 如果最小值是500，最大值是3000 效果都是好的。
最小值配置100，最大值配置30000就有问题了。

**Comment by woxingxiao** [comment]
按照你的需求，这中间总共需要290个点，这样体验友好吗？建议直接输入或者用滚轮。

**Comment by cuiyue1988** [comment]
UI图要用seekbar ...

**Comment by woxingxiao** [comment]
1080P屏幕不到4像素一个步进，720P屏幕不到3像素一个步进，小手一抖就会选差，可能你们UI没考虑到这些细节，跟UI再商讨下。

**Comment by cuiyue1988** [comment]
https://github.com/hello-eric/MinMaxSeekBar 
这个解决了我的问题。
