### ISSUE TITLE
您好，我在使用BubbleSeekBar中遇到了一些问题

### ISSUE THREAD

**Issue by 555Ge** [woxingxiao/BubbleSeekBar#23]
在我的项目中，min=20 ，max=30，
传入一个setProgress=0 ，thumb会移除seekbar范围。bubble显示的值与progress上的值不一样。

**Comment by woxingxiao** [comment]
朋友，你为何在 setProgress() 前不作判断。。

**Comment by 555Ge** [comment]
明白了，我自己的问题！
