### ISSUE TITLE
更改轨迹的大小为1dp,我把结点的原点换成了bitmap, 然后bitmap无法绘制完全

### ISSUE THREAD

**Issue by Hellozhongxin** [woxingxiao/BubbleSeekBar#25]
更改轨迹的大小为1dp,我把结点的原点换成了bitmap, 然后bitmap，在轨迹较小的时候，如1dp,2dp
bitmap无法绘制完全，上下会有缺失，请问要想把biamp绘制完成，应该调整哪些参数？

**Comment by woxingxiao** [comment]
onMeasure里根据bitmap的高度调整View的高度

**Comment by Hellozhongxin** [comment]
好的，感谢分享！
