### ISSUE TITLE
在调用setProgess()时候崩溃。。。。

### ISSUE THREAD

**Issue by woitaylor** [woxingxiao/BubbleSeekBar#26]
![_20170428001417](https://cloud.githubusercontent.com/assets/17422824/25493049/808df25c-2ba7-11e7-8d38-7482a91f19fe.png)

机型：红米Note4 
Android版本：6.0

**Comment by woxingxiao** [comment]
只能在Activity或者Fragment中使用，之前有朋友遇到了相同的问题。

**Comment by woitaylor** [comment]
我已经解决了，还是感谢作者。我出现这个错误是因为异步操作，具体情况是我Activity里面注册了EventBus事件，我退出Activity后，然后有事件过来了，在事件处理里面调用了setprogess，所以才报的这个错，后面我在ondestory注销EventBus就没这个问题了。
