### ISSUE TITLE
seekbar的bug

### ISSUE THREAD

**Issue by xxchenqi** [woxingxiao/BubbleSeekBar#27]
bubbleSeekBar1.getConfigBuilder()
                .min(1000)
                .max(10000)
                .sectionCount(9)
                .progress(5000)
                .showSectionText()
                .showSectionText()
                .showSectionMark()
                .showSectionMark()
                .seekBySection()
                .build();
当前进度设置了5000，实际只显示了3000？
是不是我姿势不对

**Comment by woxingxiao** [comment]
解决了。
