### ISSUE TITLE
问下，我把刻度隐藏之后,监听getProgressOnFinally方法就不执行了，autoAdjustSectionMark也无效了

### ISSUE THREAD

**Issue by xxchenqi** [woxingxiao/BubbleSeekBar#29]
bubbleSeekBar1.getConfigBuilder()
                .max(10000)
                .min(1000)
                .progress(5000)
                .sectionCount(9)
//                .showSectionMark()//隐藏刻度
                .autoAdjustSectionMark()
                .showSectionText()
                .sectionTextPosition(BOTTOM_SIDES)
                .build();
        bubbleSeekBar1.setOnProgressChangedListener(new BubbleSeekBar.OnProgressChangedListener() {
            @Override
            public void onProgressChanged(int progress, float progressFloat) {
                Log.i("====","onProgressChanged="+progress+"");
            }

            @Override
            public void getProgressOnActionUp(int progress, float progressFloat) {
                Log.i("====","getProgressOnActionUp="+progress+"");

            }

            @Override
            public void getProgressOnFinally(int progress, float progressFloat) {
                Log.i("====","getProgressOnFinally="+progress+"");

            }
        });

**Comment by woxingxiao** [comment]
autoAdjustSectionMark必须以showSectionMark为前提
