### ISSUE TITLE
想监听松开手得到当前进度值

### ISSUE THREAD

**Issue by catroom** [woxingxiao/BubbleSeekBar#3]
我是不是要在action up 自定写一个回调。。。还有我想在进度条左右加个加减的按钮，每按一次当前滑动一个。。。

**Comment by woxingxiao** [comment]
可以在`ACTION_UP`里的动画监听end时回调。加减按钮可以在xml里根据需要用Button、TextView或ImageView布局，监听加减按钮的`OnClick`，`mBubbleSeekBar.setProgress(mBubbleSeekBar.getProgress()±1);`

**Comment by catroom** [comment]
好的，我试一下。。。
