### ISSUE TITLE
a bug when I create a lot bubbleseekbar on one activity

### ISSUE THREAD

**Issue by heyleon** [woxingxiao/BubbleSeekBar#30]
bottom bubbleseekbar BubbleView show in wrong postion

**Comment by woxingxiao** [comment]
It's too blur  to diagnose. Can you offer me more information or take a screenshot ?

**Comment by heyleon** [comment]
Ok,its just like this 
please wait me uploding thx

**Comment by heyleon** [comment]
![qq 20170601142929](https://cloud.githubusercontent.com/assets/19371845/26667942/18389bb4-46da-11e7-9f07-67e56fa5f742.jpg)

just like this ,sorry for wait

**Comment by heyleon** [comment]
i do not   slipping ,and its normal
like this 

![Uploading QQ图片20170601142924.jpg…]()

**Comment by woxingxiao** [comment]
我还以为一位外国友人，能愉快汉语交流不。。╮(╯▽╰)╭
朋友，能多花点时间看完README文档么？里面说得很明白了，如果BubbleSeekBar的父控件是可滚动控件，需要这样修正：
```java
mContainer.setOnYourContainerScrollListener(new OnYourContainerScrollListener() {
       @Override
       public void onScroll() {
           // call this method to correct offsets
           mBubbleSeekBar.correctOffsetWhenContainerOnScrolling();
       }
   });
```

**Comment by heyleon** [comment]
哈哈....原来是自己人 ,我知道那个方法 而且我也调用了
LinearLayout lly;
lly.setOnScrollChangeListener((v, scrollX, scrollY, oldScrollX, oldScrollY) -> bu.correctOffsetWhenContainerOnScrolling());
不过还是没效果..

**Comment by woxingxiao** [comment]
你的最外层是ScrollView吧，监听ScrollView的滑动

**Comment by heyleon** [comment]
是的我也是试过了 中间的view显示位置还是不对
倒是最下面的是可以的

**Comment by woxingxiao** [comment]
我刚刚在ScrollView里放了n个，都没有任何问题。我估计你用的原生ScrollView，监听滑动需要稍微改造下。这个项目里有，叫ObservableScrollView，拿去替换下应该就可以了

**Comment by rgdzh1** [comment]
你们两个好搞笑。。。
