### ISSUE TITLE
BubbleSeekBar 和viewpager衝突問題

### ISSUE THREAD

**Issue by AlexJY** [woxingxiao/BubbleSeekBar#41]
Dear Sir

我把BubbleSeekBar 跟view pager 放在同一個fragment裡，
但是會發生 touch event 衝突(BubbleSeekBar拖曳會變得很慢)，
但移除viewpager，一切就可以正常工作，

請問要如何解決?
謝謝

**Comment by AlexJY** [comment]
This is a amazing UI component and source code.
In practice,it would be with some touch components (Viewpager/ ScrollView) together in an activity or fragment.

For touch event conflict issue,
Suggest dear sir implement a API to enable/disable requestDisallowInterceptTouchEvent on specific case.
Thus,this would be a wonderful external library, though it is now.

Thanks for your effort to improve the world better.

B.R
Alex

**Comment by woxingxiao** [comment]
Your wonderful suggestion has been received. Thank you.

**Comment by woxingxiao** [comment]
@AlexJY The touch-event conflict has been resolved since v3.6.

**Comment by AlexJY** [comment]
Thanks for your quickly response!
