### ISSUE TITLE
建议OnProgressChangedListener接口添加当前控件的参数

### ISSUE THREAD

**Issue by fly263** [woxingxiao/BubbleSeekBar#45]
类似下面这样
`   public interface OnProgressChangedListener {

        void onProgressChanged(BubbleSeekBar bubbleSeekBar, int progress, float progressFloat);

        void getProgressOnActionUp(BubbleSeekBar bubbleSeekBar, int progress, float progressFloat);

        void getProgressOnFinally(BubbleSeekBar bubbleSeekBar, int progress, float progressFloat);
    }`

这样在一个页面有多个BubbleSeekBar时可以共用一个回调，Android很多控件的回调都是带了View参数的，如View的点击回调、CheckBox的setOnCheckedChangeListener。
    public interface OnClickListener {
        /**
         * Called when a view has been clicked.
         *
         * @param v The view that was clicked.
         */
        void onClick(View v);
    }

**Comment by woxingxiao** [comment]
OK, 下个版本改进，多谢建议。
