### ISSUE TITLE
Bubble show below seekbar 

### ISSUE THREAD

**Issue by ClaudeHangui** [woxingxiao/BubbleSeekBar#54]
I don't know why, but I believe I have everything set inside the xml but the bubble keeps on appearing below the seek bar....Here's my xml : (I didn't do anything in my java class yet......I'm just trying to see how the library works. TEST DEVICE: SAMSUNG KITKAT)..

`<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
        android:id="@+id/ll_params"
        android:layout_width="match_parent"
        android:orientation="vertical"
        android:layout_height="wrap_content">

        <TextView
            android:id="@+id/tv_status"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:textSize="16sp"
            android:layout_gravity="center"
            android:textColor="@color/white"
            android:padding="8dp"/>

        <TextView
            android:id="@+id/tv_mileage"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:padding="8dp"
            android:layout_gravity="center"
            android:textColor="@color/white"
            android:textSize="16sp"/>

        <TextView
            android:id="@+id/tv_current_speed"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:padding="8dp"
            android:layout_gravity="center"
            android:textColor="@color/white"
            android:textSize="16sp"/>
    </LinearLayout>

    <com.xw.repo.BubbleSeekBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="16dp"
        app:bsb_bubble_color="@color/color_grey_light"
        app:bsb_bubble_text_color="@color/gray_holo_dark"
        app:bsb_max="100.0"
        app:bsb_progress="0"
        app:bsb_always_show_bubble="true"
        android:layout_margin="@dimen/dimen_5"
        app:bsb_thumb_text_size="18sp"
        app:bsb_second_track_color="#757575"
        app:bsb_section_count="5"
        app:bsb_section_text_position="bottom_sides"
        app:bsb_show_progress_in_float="true"
        app:bsb_show_section_mark="true"
        app:bsb_show_section_text="true"
        app:bsb_show_thumb_text="true"
        app:bsb_touch_to_seek="true"
        app:bsb_track_color="#FFFFFF"/>

</RelativeLayout>`

**Comment by woxingxiao** [comment]
Which version do you use?

**Comment by ClaudeHangui** [comment]
version 3.4...The complete version

**Comment by woxingxiao** [comment]
Try the newest one.

**Comment by abiemann** [comment]
it happens when the seekbar is within a scrollview

**Comment by abiemann** [comment]
this fixes the bubble in a scrollview:

within onCreate():
```
        BubbleSeekBar bubbleSeekBar = findViewById(R.id.seekbar);
        NestedScrollView nestedScrollView = findViewById(R.id.scrollview);
        nestedScrollView.setOnScrollChangeListener(new NestedScrollView.OnScrollChangeListener() {
            @Override
            public void onScrollChange(NestedScrollView v, int scrollX, int scrollY, int oldScrollX, int oldScrollY) {
                bubbleSeekBar.correctOffsetWhenContainerOnScrolling();
            }
        });
```

and within the XML:
```
<android.support.v4.widget.NestedScrollView
	android:id="@+id/scrollview"
	android:layout_width="match_parent"
	android:layout_height="match_parent">

	<LinearLayout
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:orientation="vertical"
		android:padding="20dp">
		
		<com.xw.repo.BubbleSeekBar
			android:id="@+id/seekbar"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:layout_marginTop="50dp"
			app:bsb_auto_adjust_section_mark="false"
			app:bsb_second_track_color="@color/color_light_blue"
			app:bsb_bubble_text_color="@color/color_black"
			app:bsb_section_count="4"
			app:bsb_section_text_position="sides"
			app:bsb_show_section_mark="true"
			app:bsb_show_section_text="true"
			app:bsb_show_thumb_text="true"
			app:bsb_thumb_text_size="18sp"
			app:bsb_touch_to_seek="true"/>
			
	</LinearLayout>

</android.support.v4.widget.NestedScrollView>
```

**Comment by ankitKamboj121** [comment]
Hi, I have an issue. Please help me

**Comment by ankitKamboj121** [comment]
I have a viewPager with 5 Fragments. In 3rd fragment, i am using Seekbar. But the seekbar bubble position is not correct. I also use below code, but no luck. Please have a look:

 viewpager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                
            }

            @Override
            public void onPageSelected(int position) {
 bubbleSeekBar.correctOffsetWhenContainerOnScrolling();
            }

            @Override
            public void onPageScrollStateChanged(int state) {

            }
        });

**Comment by woxingxiao** [comment]
@ankitKamboj121 
Where is your BubbleSeekBar? In the HostActivity or in the 3rd Fragment?

**Comment by ankitKamboj121** [comment]
in the 3rd fragment.. And i use the code
bubbleSeekBar.correctOffsetWhenContainerOnScrolling();
in host activity in view pager

**Comment by ankitKamboj121** [comment]
first it shows like this:
![screenshot_20180108-133606](https://user-images.githubusercontent.com/18529032/34662805-453b14fa-f479-11e7-8f04-19881284f147.png)

**Comment by ankitKamboj121** [comment]
And when i minimize and maximize the app, then shows like this:

![screenshot_20180108-133557](https://user-images.githubusercontent.com/18529032/34662816-589690c4-f479-11e7-902b-a8841d478820.png)

**Comment by woxingxiao** [comment]
After `findViewById`, do:
```java
bubbleSeekBar.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                bubbleSeekBar.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                bubbleSeekBar.correctOffsetWhenContainerOnScrolling();
                }
        });
```

**Comment by ankitKamboj121** [comment]
ok..Let me check. Thanks

**Comment by ankitKamboj121** [comment]
No, Same issue happens.

**Comment by woxingxiao** [comment]
@ankitKamboj121 Which version do you use?

**Comment by ankitKamboj121** [comment]
I used lib as project module

**Comment by woxingxiao** [comment]
I mean...is it version 3.13?

**Comment by ankitKamboj121** [comment]
yes

**Comment by ankitKamboj121** [comment]
def VERSION_NAME = "3.13"

**Comment by woxingxiao** [comment]
ok, I will investigate that.

**Comment by ankitKamboj121** [comment]
OK. Thanks. Please do it ASAP because i need it today.

**Comment by ankitKamboj121** [comment]
And how to remove internal padding in seekbar?

**Comment by woxingxiao** [comment]
@ankitKamboj121 Have you set `bsb_always_show_bubble="true"`?
