### ISSUE TITLE
Bubble position does not update when seekbar position changes.

### ISSUE THREAD

**Issue by edTheGuy00** [woxingxiao/BubbleSeekBar#61]
I have paced the seekbar in a DialogFragment. When opening the keyboard the seekbar position chages but the bubble position does not update. 

![img_20170928_221449](https://user-images.githubusercontent.com/16095735/30975123-a3189a26-a49b-11e7-9470-abe8c3cbf9c8.jpg)

**Comment by woxingxiao** [comment]
Listen to soft keyboard show or hide event, then call: 
```java
mBubbleSeekBar.correctOffsetWhenContainerOnScrolling();
```

**Comment by kevinzo22** [comment]
@edTheGuy00 how did you solve this? I'm trying to do correctOffsetWhenContainerOnScrolling() when keyboard is showing or hiding but it's not really working for me :(

**Comment by UmarAlyas0078** [comment]
### **Defult values** 
mBubbleCenterRawSolidY += dp2px(2);
        if (BubbleUtils.isMIUI()) {
            mBubbleCenterRawSolidY += dp2px(2);
        }

### ChangeAble Valus
### After this the bubble view position will be change good luck
  mBubbleCenterRawSolidY += dp2px(120);
        if (BubbleUtils.isMIUI()) {
            mBubbleCenterRawSolidY += dp2px(120);
        }
