### ISSUE TITLE
Callback overhead

### ISSUE THREAD

**Issue by neymoura** [woxingxiao/BubbleSeekBar#62]
Hey!

Is there any reason for the `BubbleSeekBar.OnProgressChangedListener().OnProgressChanged()`
be called all the time? Even if the progress won't change at all? It does really affect the performance of the apps using it.

I'm currently using the int mode, not the float one. I fixed this issue by adding a variable that stores the last progress, this way I could avoid unnecessary code execution.

Here is my example:

`
int presencas = 0;
int aulas = 3;

int lastProgress = presencas;

seekBar.getConfigBuilder()
                .min(0)
                .max(aulas)
                .sectionCount(aulas)
                .progress(presencas)
                .build();

seekBar.setOnProgressChangedListener(new BubbleSeekBar.OnProgressChangedListener() {

            @Override
            public void onProgressChanged(BubbleSeekBar bubbleSeekBar, int progress, float progressFloat) {

                if(lastProgress != progress){

                    lastProgress = progress;

                    if(progress == 0){
                        //Falta
                        setSecondTrackColor(bubbleSeekBar, R.color.frequencia_falta);
                    }else if(progress == totalAulas){
                        //Presenca
                        setSecondTrackColor(bubbleSeekBar, R.color.frequencia_total);
                    }else{
                        //Parcial
                        setSecondTrackColor(bubbleSeekBar, R.color.frequencia_parcial);
                    }

                }

            }

            @Override
            public void getProgressOnActionUp(BubbleSeekBar bubbleSeekBar, int progress, float progressFloat) {

            }

            @Override
            public void getProgressOnFinally(BubbleSeekBar bubbleSeekBar, int progress, float progressFloat) {
                onOptionSelectListener.selected(progress);
            }

        });`

**Comment by neymoura** [comment]
BTW, I'm using full 3.7 version and here's my xml:

`
<com.xw.repo.BubbleSeekBar
        android:id="@+id/seek_bar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/nav_header_separator"
        android:layout_margin="16dp"
        app:bsb_min="0"
        app:bsb_max="4"
        app:bsb_section_count="4"
        app:bsb_touch_to_seek="true"
        app:bsb_auto_adjust_section_mark="true"
        app:bsb_second_track_color="@color/frequencia_parcial"
        app:bsb_track_color="@color/colorAccent"
        app:bsb_section_text_position="below_section_mark"
        app:bsb_show_section_mark="true"
        app:bsb_show_section_text="true"
        app:bsb_show_thumb_text="true"
        />
`

**Comment by woxingxiao** [comment]
I guess you wanted to change the `secondTrackColor` dynamically by using `ConfigBuilder`. In fact, every time you call `configBuilder.build()`, the `OnProgressChangedListener` will response. As your solution, it needs to be improved to do better.
