### ISSUE TITLE
关于自定义最后一个文字

### ISSUE THREAD

**Issue by Hhh3S** [woxingxiao/BubbleSeekBar#69]
您好，我有一个这样的需求，希望最后一个文字可以自定义，例如最后显示刻度的单位。值需要保持不变，请问有提供这样的功能吗？
![issue_bubbleseekbar](https://user-images.githubusercontent.com/17513523/31870734-1621d038-b7e2-11e7-987d-7df4940deb42.png)

**Comment by woxingxiao** [comment]
不考虑单独为特俗需求做一个attr。
你这个需求简单，你自己在源码基础上最后一位加一个汉字就行了。

**Comment by Hhh3S** [comment]
目前我就是更改源码去做的，发现大字体，英文语言状态下，适配有点问题。会遮挡最后一个字母。我再去看看源码吧，Thank you！
