### ISSUE TITLE
BubbleView position misplaced in free-form mode.

### ISSUE THREAD

**Issue by AwenHuang** [woxingxiao/BubbleSeekBar#75]
Hi

Your work is great! I like the visual effect of bubble. Here is my problem: 

When I use the BubbleSeekBar in free-form mode (multi-window mode), the BubbleView didn't show on the track.  Could you fix that problem? Thanks!

嗨~ 當我在多視窗模式下開啟使用BubbleSeekBar的APP，在拉動Seekbar時，氣泡顯示的位置會錯亂，並不在track上，可能計算位置的時候需要再考慮下是不是視窗模式? 不知您是否能解決這個問題呢，感謝

**Comment by AwenHuang** [comment]
Thanks for reply!

free-form mode is like this
http://www.androidpolice.com/wp-content/uploads/2016/06/nexus2cee_Multiwindow-728x546.png

**Comment by manadragon** [comment]
Hi ... 
I had a similar problem.
position not match... on the scroll able view .

**Comment by woxingxiao** [comment]
I'm afraid it's unavailable to use the `BubbleSeekBar` in free-mode under multi-window mode because the location of the window can't be located on the screen.
