### ISSUE TITLE
BubbleSeekbar position problem in a tabLayout

### ISSUE THREAD

**Issue by lucamar88** [woxingxiao/BubbleSeekBar#76]
Hi, I have used the bubbleseek in a View with a tabLayout and a scroll (NestedScrollView), in particular, there are 5 seekBar for each tab (4 tab in total). When I open the tabs for the first time everything is ok but when I change the tab the "bubble" stays in the wrong position. So if I scroll the view the bubbles return in the right position, I have used the correctOffsetWhenContainerOnScrolling() method. I am trying to use the same method when the tab changes but it doesn't work. Can you please help me?

**Comment by woxingxiao** [comment]
You should listen to the Tab changing and call `correctOffsetWhenContainerOnScrolling()` as well.
