### ISSUE TITLE
Exception: BubbleSeekBar$BubbleView not attached to window manager

### ISSUE THREAD

**Issue by abiemann** [woxingxiao/BubbleSeekBar#80]
Simply by tapping all around and dragging the slider, it's possible to trigger this exception:

> 11-12 22:25:02.984 4293-4293/com.my.app E/InputEventReceiver: Exception dispatching input event.
> 11-12 22:25:02.985 4293-4293/com.my.app D/AndroidRuntime: Shutting down VM
> 11-12 22:25:02.986 4293-4293/com.my.app E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                        Process: com.my.app, PID: 4293
>                                                                        java.lang.IllegalArgumentException: View=com.xw.repo.BubbleSeekBar$BubbleView{3a531c6 V.ED..... ......ID 0,0-144,144} not attached to window manager
>                                                                            at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:470)
>                                                                            at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:365)
>                                                                            at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:101)
>                                                                            at com.xw.repo.BubbleSeekBar.onTouchEvent(BubbleSeekBar.java:674)
>                                                                            at android.view.View.dispatchTouchEvent(View.java:10072)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
>                                                                            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
>                                                                            at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
>                                                                            at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
>                                                                            at android.app.Activity.dispatchTouchEvent(Activity.java:3102)
>                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
>                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
>                                                                            at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
>                                                                            at android.view.View.dispatchPointerEvent(View.java:10292)
>                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
>                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
>                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
>                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
>                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
>                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
>                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
>                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
>                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
>                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
>                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
>                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
>                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
>                                                                            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6252)
>                                                                            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6226)
>                                                                            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6187)
>                                                                            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6355)
>                                                                            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
> 11-12 22:25:02.987 4293-4293/com.my.app E/AndroidRuntime:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
>                                                                            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
>                                                                            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6326)
>                                                                            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6378)
>                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
>                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
>                                                                            at android.view.Choreographer.doFrame(Choreographer.java:615)
>                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
>                                                                            at android.os.Handler.handleCallback(Handler.java:751)
>                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                            at android.os.Looper.loop(Looper.java:241)
>                                                                            at android.app.ActivityThread.main(ActivityThread.java:6274)
>                                                                            at java.lang.reflect.Method.invoke(Native Method)
>                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**The XML I used is:**

                    <com.xw.repo.BubbleSeekBar
                        android:id="@+id/seekbar"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:layout_marginTop="50dp"
                        app:bsb_auto_adjust_section_mark="false"
                        app:bsb_second_track_color="@color/color_light_blue"
                        app:bsb_bubble_text_color="@color/color_black"
                        app:bsb_section_count="4"
                        app:bsb_section_text_position="sides"
                        app:bsb_show_section_mark="true"
                        app:bsb_show_section_text="true"
                        app:bsb_show_thumb_text="true"
                        app:bsb_thumb_text_size="18sp"
                        app:bsb_touch_to_seek="true"/>

**Comment by abiemann** [comment]
Note, I am using: **com.xw.repo:bubbleseekbar:3.9**

**Comment by abiemann** [comment]
It's possible that the pull request will fix it:
https://github.com/woxingxiao/BubbleSeekBar/pull/63/commits/a078f326ffdeeece37fe11f3ac738b72f18ebb29

**Comment by abiemann** [comment]
method to reproduce the exception really easily:
1) load the app, with the seekbar, on the emulator.
2) with your mouse, select the seekbar. Then scroll the middle wheel up and down. Exception will happen.

**Comment by woxingxiao** [comment]
In fact, there is no chance to occur this exception on your real phone, because the seekbar is handling the touch event while its parent can't respond at the same time.
BTW, thank you for your reporting.
