### ISSUE TITLE
getProgressOnFinally无效

### ISSUE THREAD

**Issue by ShineYang** [woxingxiao/BubbleSeekBar#81]
使用的 3.8 的 enhance 版本，之前 #29 的 issue 问题类似。
`seekBar.getConfigBuilder()
                .min(0)
                .max(Integer.valueOf(getPages()))
                .progress(getProgress())
                .build();

        //进度手势监听
        seekBar.setOnProgressChangedListener(new BubbleSeekBar.OnProgressChangedListener() {
            @Override
            public void onProgressChanged(BubbleSeekBar bubbleSeekBar, int i, float v) {
//滑动中有效
            }

            @Override
            public void getProgressOnActionUp(BubbleSeekBar bubbleSeekBar, int i, float v) {
//滑动中有效
            }

            @Override
            public void getProgressOnFinally(BubbleSeekBar bubbleSeekBar, int i, float v) {
                Logger.v("-----手动设置进度:" + i);
                // 滑动结束后此方法不走
            }
        });`

**Comment by woxingxiao** [comment]
1. `getProgressOnFinally()`的设计只针对autoAdjustSectionMark（手指离开后，seek可能自动滑向最近section处）时生效。非此情况，所滑即所得，前面两个监听够你用了。
2. 如果你嫌这个方法碍眼，可以使用`OnProgressChangedListenerAdapter`选择性重写你需要的监听。
3. 你提到的issue，你只看到问题没看到下面还有我的解答吗。
4. 尽量用最新版，目前是3.9。

**Comment by ShineYang** [comment]
issue都看过一遍，只是没理解你下面的回复内容才提的新issue。
这次明白了，感谢回复🙏  。
