### ISSUE TITLE
duplicate definition in manifest: app_name

### ISSUE THREAD

**Issue by abiemann** [woxingxiao/BubbleSeekBar#84]
Hi - could you please remove the _app_name_ definition from your strings.xml? It conflicts with my app (and probably for everyone else too)

**Specific error message:**

Error:Execution failed for task ':app:processDevelopmentDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/APP_NAME) from AndroidManifest.xml:26:9-41
  	is also present at [com.xw.repo:bubbleseekbar:3.9] AndroidManifest.xml:13:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:21:5-90:19 to override.

**Comment by woxingxiao** [comment]
I have not encountered this problem yet. However, you had found the solution already yourself: 
>add 'tools:replace="android:label"' to element at AndroidManifest.xml(your app's Androidmanifest.xml has the highest priority)

Go check more info [https://developer.android.com/studio/build/manifest-merge.html](https://developer.android.com/studio/build/manifest-merge.html)
,

**Comment by abiemann** [comment]
indeed, I've added 'tools:replace="android:label"' to my manifest - it's not usual though. Additionally, a library doesn't need that string.
