### ISSUE TITLE
mThumbRadiusOnDragging  读取的时候值附错了

### ISSUE THREAD

**Issue by 9468lgy** [woxingxiao/BubbleSeekBar#85]
当把进度条宽度改的比较细的时候，会出现thumb显示不全的情况
mThumbRadiusOnDragging = a.getDimensionPixelSize(R.styleable.BubbleSeekBar_bsb_thumb_radius,
                mSecondTrackSize * 2);
应该改为，
mThumbRadiusOnDragging = a.getDimensionPixelSize(R.styleable.BubbleSeekBar_bsb_thumb_radius_on_dragging,
                mSecondTrackSize * 2);

**Comment by woxingxiao** [comment]
ok，下个版本改回来。
