### ISSUE TITLE
Bubble misplaced in scrollview

### ISSUE THREAD

**Issue by efreville** [woxingxiao/BubbleSeekBar#87]
Hello,

I use a BubbleSeekBar in a ConstraintLayout, which is in a ScrollView.
I add an onTouchListener on my ScrollView, where I call correctOffsetWhenContainerOnScrolling(), but the bubble keeps being in the same place.

How can I replace the bubble in the correct position?

Thank you,
Elodie.

**Comment by woxingxiao** [comment]
You should extend the ScrollView to listen it's scroll states, which had been demonstrated in my sample.

**Comment by efreville** [comment]
Thank you for your fast response.

I've extended the ScrollView exactly as you did, and set a listener:

`scrollView.setOnScrollChangedListener(object : ObservableScrollView.OnScrollChangedListener {
            override fun onScrollChanged(scrollView: ObservableScrollView, x: Int, y: Int, oldx: Int, oldy: Int) {
                simu_ts_duration_seekbar.correctOffsetWhenContainerOnScrolling()
            }
        })`

The implementation of ObservableScrollView is the same as your sample.

But unfortunately, the bubble still keeps being at the same position.

Is it because the seekbar is contained in a ConstraintLayout that is contained in a ObservableScrollView?

**Comment by efreville** [comment]
Here is my xml code for my seekbar:

`<com.xw.repo.BubbleSeekBar
            app:bsb_always_show_bubble="true"
            app:bsb_auto_adjust_section_mark="true"
            app:bsb_max="30"
            app:bsb_min="5"
            app:bsb_second_track_color="@color/pink"
            app:bsb_section_count="20"
            app:bsb_section_text_color="@color/purple"
            app:bsb_section_text_interval="4"
            app:bsb_section_text_position="below_section_mark"
            app:bsb_show_section_mark="true"
            app:bsb_show_section_text="true"
            app:bsb_touch_to_seek="true"
            app:bsb_track_color="@color/grey" />`

**Comment by woxingxiao** [comment]
I think the ContstraintLayout is related to this matter, so I suggest you try another root layout for now. When the time is available, I'll try to find a solution.
