### ISSUE TITLE
Disabling smooth seeking

### ISSUE THREAD

**Issue by HusseinElFeky** [woxingxiao/BubbleSeekBar#89]
I would like a new feature that enables/disables smooth seeking in the BubbleSeekBar. For example, when `max` is set to 4, when I seek to another value, it doesn't seek to there instantly, but instead it animates the change by smooth seeking to that position. I would like to disable that and let the thumb be seeked to that new position instantly without any animation or smooth seeking just as the normal SeekBar. This would be extremely useful when setting `section_count` as the `max` value especially when the value is small.

**Comment by woxingxiao** [comment]
You can set `bsb_anim_duration = 0`, or set `bsb_hide_bubble = true` to be a normal SeekBar.

**Comment by HusseinElFeky** [comment]
Thanks for your reply, but this did not solve the issue. When I seek the thumb to a certain value, it gets animated if I don't remove my finger. Another explanation is that when I keep touching the thumb and seek it to a certain position and I am *still* touching the thumb, the thumb gets moved smoothly with my finger wherever it goes, and I do not want that. I want it to be seeked to the nearest value. The values are of int type, not float.

**Comment by HusseinElFeky** [comment]
Thanks for your reply, but this did not solve the issue. When I seek the thumb to a certain value, it gets animated if I don't remove my finger. Another explanation is that when I keep touching the thumb and seek it to a certain position and I am **still** touching the thumb, the thumb gets moved smoothly with my finger wherever it goes, and I do not want that. I want it to be seeked to the nearest value. The values are of int type, not float.

**Comment by HusseinElFeky** [comment]
Thanks for your reply, but this did not solve the issue. I will try to explain my issue better.

When I seek the thumb to a certain value, it gets animated if I don't remove my finger. Another explanation is that when I keep touching the thumb and seek it to a certain position and I am **still** touching the thumb, the thumb gets moved smoothly with my finger wherever it goes, and I do not want that. I want it to be seeked to the nearest value instantly. The values are of int type, not float, and `max` is so small like `4`, thus I do not need smooth seeking because it looks unrealistic.

**Comment by woxingxiao** [comment]
Now I get it. Perhaps setting `bsb_auto_adjust_section_mark = true`  and `bsb_seek_by_section= true`  will work.

**Comment by HusseinElFeky** [comment]
I tried as you said, but still no difference.

Here is an example:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="16dp">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="SeekBar (desired action)" />

    <SeekBar
        android:id="@+id/seekBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="20dp"
        android:layout_marginTop="20dp"
        android:max="4"
        android:progress="0" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="BubbleSeekBar" />

    <com.xw.repo.BubbleSeekBar
        android:id="@+id/bubbleSeekBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="20dp"
        android:layout_marginTop="20dp"
        app:bsb_anim_duration="0"
        app:bsb_auto_adjust_section_mark="true"
        app:bsb_is_float_type="false"
        app:bsb_max="4"
        app:bsb_progress="0"
        app:bsb_section_count="4"
        app:bsb_seek_by_section="true"
        app:bsb_touch_to_seek="true" />

</LinearLayout>
```

![Example](https://user-images.githubusercontent.com/20887574/33540058-ef89fe4e-d8d1-11e7-8f1a-f9faf0caaa59.gif)

**Comment by woxingxiao** [comment]
Sorry, the BubbleSeekBar only supports smooth seeking for now. However, your desired action seemed more easily, you can do it your self.

**Comment by HusseinElFeky** [comment]
Can't it be implemented sometime in the future? I liked this library because of the sections.

**Comment by woxingxiao** [comment]
Maybe next version. I'll do my best : )

**Comment by HusseinElFeky** [comment]
That's great. Thanks. 😄

**Comment by woxingxiao** [comment]
@HusseinElFeky New version has been released finally. Enjoy.

**Comment by HusseinElFeky** [comment]
Great job as always! Thanks.

**Comment by HusseinElFeky** [comment]
Awesome work as always! Thanks.
