### ISSUE TITLE
Bubble view not visible on 27 SDK

### ISSUE THREAD

**Issue by i-petro** [woxingxiao/BubbleSeekBar#92]
Awesome library!
I discovered one problem: bubble view is not visible on 27 SDK (Oreo), but works as well on 21 SDK (Lollipop). 
XML:
`<com.xw.repo.BubbleSeekBar
        android:id="@+id/sbRadius"
        android:layout_marginTop="300dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:bsb_auto_adjust_section_mark="true"
        app:bsb_second_track_color="@color/colorAccent"
        app:bsb_section_count="5"
        app:bsb_section_text_position="below_section_mark"
        app:bsb_show_section_mark="true"
        app:bsb_show_section_text="true"
        app:bsb_show_thumb_text="true"
        app:bsb_thumb_text_size="18sp"
        app:bsb_touch_to_seek="true"
        />`
![bug](https://user-images.githubusercontent.com/12115164/33573125-9b040466-d93d-11e7-8857-1cf7b1e7eb40.png)
![bug2](https://user-images.githubusercontent.com/12115164/33573239-ec0bed24-d93d-11e7-90d2-792ae82b860b.png)

**Comment by zzm123456** [comment]
我的Android N也看不到泡泡 直接克隆下来的项目

**Comment by woxingxiao** [comment]
@i-petro @zzm123456 Have been fixed. Thanks for your reporting.
