### ISSUE TITLE
Correcting offset when scrolling is not working 

### ISSUE THREAD

**Issue by kevinzo22** [woxingxiao/BubbleSeekBar#99]
First of all, thanks for this amazing library! Awesome job! 

Then, using this structure:
ScrollView
   ConstraintLayout
      TextView
      BubbleSeekBar
      TextView
      BubbleSeekBar
      TextView
      BubbleSeekBar      
      EdiText
      Button

I'm trying to correct the offset of each BubbleSeekBar using correctOffsetWhenContainerOnScrolling() each time the user scrolls, but it's not working and the position of the bubbles are wrong after scrolling. 

In addition, I have a left tab at the app, and when I open/swipe the tab to the right, the bubbles appear over the tab while the rest of the seekbar is normally displayed (not seen, under the tab). Happened the same when I locked the phone, the bubble still appear above the Always On screen on a Samsung device for example.

Finally, after locking and unlocking the phone, at some point, I get this error while trying to tap one SeekBar:

![capture2](https://user-images.githubusercontent.com/32536918/34664451-43f730fa-f45c-11e7-9b61-7bf81bfe630b.PNG)

![capture22](https://user-images.githubusercontent.com/32536918/34664489-6f2ab9e0-f45c-11e7-9f64-7beb47ac82d3.PNG)

I've tried it on these devices:
Samsung S8+ with Android 7.0
Google Pixel with Android 8.1.0

Thanks in advance!

Cheers,
Kevin

**Comment by woxingxiao** [comment]
@kevinzo22 
Hi Kevin, I have tried the exactly way according to your description, which turned out worked completely fine. BTW, the Bubble must on the top of all views if you wonder.
1. Have you used the latest version?
2. Have you listened to the scrolling event of the  `ScrollView` correctly?
3. Have you set `bsb_always_show_bubble="true"`?

**Comment by kevinzo22** [comment]
@woxingxiao thanks for your quick answer!

Regarding your questions:
1. I'm using 'com.xw.repo:bubbleseekbar:3.13-lite'. Is the last one, right?
2. Already checked and the event is working properly.
3. bsb_always_show_bubble="true" is set for the three SeekBars.

But I'm wondering that could be related to the thing that the Bubble must be on top of all views. How could that be achieved? I have all the items listed above (TextView, BubbleSeekBar, EdiText, Button) inside of the ConstraintLayout.

In addition, my minSdkVersion is 19. Could this be related to the issue?

Thanks again! :)

**Comment by woxingxiao** [comment]
The bubble is added via `WindowManager.addView()`, so it doesn't relate to your ViewGroup.
V3.14 has fixed the wrong position of the bubble while scrolling when the bubble always shows.

**Comment by woxingxiao** [comment]
@kevinzo22 Did it work?

**Comment by IamKing** [comment]
@kevinzo22 Please look at my solution, it supports RecyclerView, ListView, ScrollView
[https://github.com/woxingxiao/BubbleSeekBar/issues/101](url)

**Comment by kevinzo22** [comment]
@woxingxiao thanks a lot for the quick fix! So now after scrolling the bubble position is correct, but still when I scroll all the way down, it appears above of a top toolbar I have. Same thing happens when I swipe in my left menu, the bubble appears on top of the menu (shouldn't be seen). But seems to be related to that the Bubble must be on top of all views, and it's not right now.

@IamKing thanks for the input! I'll check it! :)

**Comment by woxingxiao** [comment]
@kevinzo22 Considered your special demands, maybe [this repo](https://github.com/warkiz/IndicatorSeekBar) is more suitable for you.
